---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
require_paths: ['../../.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems']
max_files: 5000
